name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Push Docker image to registry
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.duong27062002 }}
        password: ${{ secrets.27062002 }}
        repository: username/repository
        tag_with_ref: true
