name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        node-version: '20'   # Cập nhật để sử dụng Node.js 20

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

  build:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Docker image
      if: success()   # Chỉ chạy nếu các bài kiểm tra đơn vị thành công
      run: docker build -t myapp .

    - name: Push Docker image to registry
      if: success()   # Chỉ chạy nếu các bài kiểm tra đơn vị thành công
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: username/repository
        tag_with_ref: true

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to Cloud Server
  run: |
    echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa
    scp -o StrictHostKeyChecking=no myapp user@cloud-server:/path/to/destination
    ssh -o StrictHostKeyChecking=no user@cloud-server 'cd /path/to/destination && docker-compose up -d'
