name: CI/CD and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: myapp
          path: .  # Đường dẫn tới các tệp cần lưu trữ

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: myapp

      - name: Deploy to Processor
        run: |
          cp -r ./myapp/* /path/to/your/processor
          echo "Deployment completed"
