name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          npm run build

      - name: Test
        run: npm test

      - name: Deploy
        uses: easingthemes/ssh-deploy@v2
        with:
          server_ip: ${{ secrets.SERVER_IP }}
          server_username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          local_dir: 'build'
          remote_dir: '/var/www/html'
