name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        node-version: '20'   # Cập nhật để sử dụng Node.js 20

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Build Docker image
      if: ${{ job.status == 'success' }}   # Chỉ chạy nếu các bài kiểm tra đơn vị thành công
      run: docker build -t myapp .

    - name: Push Docker image to registry
      if: ${{ job.status == 'success' }}   # Chỉ chạy nếu các bài kiểm tra đơn vị thành công
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: username/repository
        tag_with_ref: true