name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install PlatformIO Core
      run: |
        pip install platformio

    - name: Build and Generate BIN
      run: |
        platformio run --environment genericSTM32F103C8

    - name: List files after build
      run: ls firmware/

    - name: Display firmware.bin content
      run: xxd firmware/firmware.bin

    - name: Upload BIN Artifact
      uses: actions/upload-artifact@v2
      with:
        name: firmware.bin
        path: firmware/firmware.bin
