name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        node-version: '20'   # Cập nhật để sử dụng Node.js 20

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Push Docker image to registry
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_duong27062002 }}
        password: ${{ secrets.DOCKER_27062002 }}
        repository: username/repository
        tag_with_ref: true
