name: Build and Deploy

on:
  push:
    branches:
      - main  # Thay đổi tên nhánh nếu bạn sử dụng nhánh khác

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install PlatformIO Core
      run: |
        pip install platformio

    - name: Build and Generate HEX
      run: |
        platformio run --target build --environment genericSTM32F103C8

    - name: Upload HEX Artifact
      uses: actions/upload-artifact@v2
      with:
        name: firmware.hex
        path: .pio/build/genericSTM32F103C8/firmware.hex
