name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install PlatformIO Core
      run: |
        pip install platformio

    - name: Build and Generate BIN
      run: |
        platformio run --environment genericSTM32F103C8

    - name: Get firmware.bin from FTP
      run: |
        lftp -c "open -u demo,password -p 21 test.rebex.net && get firmware.bin -o firmware.bin"
      continue-on-error: true

    - name: Get main.cpp from FTP
      run: |
        lftp -c "open -u demo,password -p 21 test.rebex.net && get main.cpp -o main.cpp"
      continue-on-error: true

    - name: Upload BIN Artifact
      uses: actions/upload-artifact@v2
      with:
        name: firmware.bin
        path: .pio/build/genericSTM32F103C8/firmware.bin

    - name: Upload main.cpp to GitHub Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: main.cpp
        path: src/main.cpp
