name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install PlatformIO Core
      run: |
        pip install platformio

    - name: Build and Generate BIN
      run: |
        platformio run --environment genericSTM32F103C8

    - name: List files after build
      run: ls .pio/build/genericSTM32F103C8/

    - name: Display firmware.bin content
      run: xxd .pio/build/genericSTM32F103C8/firmware.bin

    - name: Upload BIN Artifact
      uses: actions/upload-artifact@v2
      with:
        name: firmware.bin
        path: .pio/build/genericSTM32F103C8/firmware.bin

    - name: Upload to FTP
      run: |
        echo "put .pio/build/genericSTM32F103C8/firmware.bin" | ftp -n -v 103.97.126.29 21 -u jqgsqvdj,27062002
        echo "put src/main.cpp /domains/nvduong.tt/CODE_FTP/main.cpp" | ftp -n -v 103.97.126.29 21 -u jqgsqvdj,27062002
      env:
        FTP_USER: jqgsqvdj
        FTP_PASSWORD: 27062002
