name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install PlatformIO Core
      run: |
        pip install platformio

    - name: Build and Generate BIN
      run: |
        platformio run --environment genericSTM32F103C8

    - name: List files after build
      run: ls .pio/build/genericSTM32F103C8/

    - name: Display firmware.bin content
      run: xxd .pio/build/genericSTM32F103C8/firmware.bin

    - name: Upload BIN Artifact
      uses: actions/upload-artifact@v2
      with:
        name: firmware.bin
        path: .pio/build/genericSTM32F103C8/firmware.bin

    - name: Create FTP_ALL directory
      run: mkdir -p C:\Users\nvduo\OneDrive\Desktop\FTP_ALL

    - name: Copy firmware.bin to FTP_ALL directory
      run: cp .pio/build/genericSTM32F103C8/firmware.bin C:\Users\nvduo\OneDrive\Desktop\FTP_ALL/

    - name: Copy source files to FTP_ALL directory
      run: cp -R C:\Users\nvduo\TEST_DTTT\test_DTTT\src\* C:\Users\nvduo\OneDrive\Desktop\FTP_ALL/

    - name: Upload FTP_ALL directory to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: 103.97.126.29
        username: jqgsqvdj
        password: 27062002
        local-dir: C:\Users\nvduo\OneDrive\Desktop\FTP_ALL
        server-dir: /domains/nvduong.tt/FTP_ALL
