name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy
        # Add your deployment steps here, such as deploying to a cloud platform
