name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        node-version: '20'   # Cập nhật để sử dụng Node.js 20

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

  build:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Docker image
      if: success()   # Chỉ chạy nếu các bài kiểm tra đơn vị thành công
      run: docker build -t myapp .

    - name: Push Docker image to registry
      if: success()   # Chỉ chạy nếu các bài kiểm tra đơn vị thành công
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: username/repository
        tag_with_ref: true
  deploy:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Build Website
      run: npm run build   # Thay thế lệnh này bằng lệnh thực sự để xây dựng trang web của bạn

    - name: Deploy to GitHub Pages
      if: success()   # Chỉ chạy nếu việc xây dựng thành công
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./path/to/your/website
        cname: yourdomain.com   # Tùy chọn: nếu bạn muốn sử dụng tên miền tùy chỉnh
